<?php
use Migrations\AbstractSeed;

/**
 * Acos seed.
 */
class AcosSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'parent_id' => NULL,
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'controllers',
                'lft' => '1',
                'rght' => '150',
            ],
            [
                'id' => '2',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Error',
                'lft' => '2',
                'rght' => '3',
            ],
            [
                'id' => '3',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Pages',
                'lft' => '4',
                'rght' => '7',
            ],
            [
                'id' => '4',
                'parent_id' => '3',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'display',
                'lft' => '5',
                'rght' => '6',
            ],
            [
                'id' => '5',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Acl',
                'lft' => '8',
                'rght' => '9',
            ],
            [
                'id' => '6',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'AdminPanel',
                'lft' => '10',
                'rght' => '115',
            ],
            [
                'id' => '7',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Dashboard',
                'lft' => '11',
                'rght' => '22',
            ],
            [
                'id' => '8',
                'parent_id' => '7',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '12',
                'rght' => '13',
            ],
            [
                'id' => '9',
                'parent_id' => '7',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '14',
                'rght' => '15',
            ],
            [
                'id' => '10',
                'parent_id' => '7',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '16',
                'rght' => '17',
            ],
            [
                'id' => '11',
                'parent_id' => '7',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '18',
                'rght' => '19',
            ],
            [
                'id' => '12',
                'parent_id' => '7',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '20',
                'rght' => '21',
            ],
            [
                'id' => '13',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Users',
                'lft' => '23',
                'rght' => '40',
            ],
            [
                'id' => '14',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '24',
                'rght' => '25',
            ],
            [
                'id' => '15',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'password',
                'lft' => '26',
                'rght' => '27',
            ],
            [
                'id' => '16',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '28',
                'rght' => '29',
            ],
            [
                'id' => '17',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '30',
                'rght' => '31',
            ],
            [
                'id' => '18',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '32',
                'rght' => '33',
            ],
            [
                'id' => '19',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '34',
                'rght' => '35',
            ],
            [
                'id' => '20',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'login',
                'lft' => '36',
                'rght' => '37',
            ],
            [
                'id' => '21',
                'parent_id' => '13',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'logout',
                'lft' => '38',
                'rght' => '39',
            ],
            [
                'id' => '22',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Bake',
                'lft' => '116',
                'rght' => '117',
            ],
            [
                'id' => '23',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'DebugKit',
                'lft' => '118',
                'rght' => '145',
            ],
            [
                'id' => '24',
                'parent_id' => '23',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Composer',
                'lft' => '119',
                'rght' => '122',
            ],
            [
                'id' => '25',
                'parent_id' => '24',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'checkDependencies',
                'lft' => '120',
                'rght' => '121',
            ],
            [
                'id' => '26',
                'parent_id' => '23',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'MailPreview',
                'lft' => '123',
                'rght' => '130',
            ],
            [
                'id' => '27',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '124',
                'rght' => '125',
            ],
            [
                'id' => '28',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'sent',
                'lft' => '126',
                'rght' => '127',
            ],
            [
                'id' => '29',
                'parent_id' => '26',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'email',
                'lft' => '128',
                'rght' => '129',
            ],
            [
                'id' => '30',
                'parent_id' => '23',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Panels',
                'lft' => '131',
                'rght' => '136',
            ],
            [
                'id' => '31',
                'parent_id' => '30',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '132',
                'rght' => '133',
            ],
            [
                'id' => '32',
                'parent_id' => '30',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '134',
                'rght' => '135',
            ],
            [
                'id' => '33',
                'parent_id' => '23',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Requests',
                'lft' => '137',
                'rght' => '140',
            ],
            [
                'id' => '34',
                'parent_id' => '33',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '138',
                'rght' => '139',
            ],
            [
                'id' => '35',
                'parent_id' => '23',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Toolbar',
                'lft' => '141',
                'rght' => '144',
            ],
            [
                'id' => '36',
                'parent_id' => '35',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'clearCache',
                'lft' => '142',
                'rght' => '143',
            ],
            [
                'id' => '37',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Migrations',
                'lft' => '146',
                'rght' => '147',
            ],
            [
                'id' => '38',
                'parent_id' => '1',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'WyriHaximus\\TwigView',
                'lft' => '148',
                'rght' => '149',
            ],
            [
                'id' => '39',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Groups',
                'lft' => '41',
                'rght' => '54',
            ],
            [
                'id' => '40',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '42',
                'rght' => '43',
            ],
            [
                'id' => '41',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '44',
                'rght' => '45',
            ],
            [
                'id' => '42',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'sync',
                'lft' => '46',
                'rght' => '47',
            ],
            [
                'id' => '43',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '48',
                'rght' => '49',
            ],
            [
                'id' => '44',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '50',
                'rght' => '51',
            ],
            [
                'id' => '45',
                'parent_id' => '39',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '52',
                'rght' => '53',
            ],
            [
                'id' => '52',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Districts',
                'lft' => '55',
                'rght' => '66',
            ],
            [
                'id' => '53',
                'parent_id' => '52',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '56',
                'rght' => '57',
            ],
            [
                'id' => '54',
                'parent_id' => '52',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '58',
                'rght' => '59',
            ],
            [
                'id' => '55',
                'parent_id' => '52',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '60',
                'rght' => '61',
            ],
            [
                'id' => '56',
                'parent_id' => '52',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '62',
                'rght' => '63',
            ],
            [
                'id' => '57',
                'parent_id' => '52',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '64',
                'rght' => '65',
            ],
            [
                'id' => '58',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Provinces',
                'lft' => '67',
                'rght' => '78',
            ],
            [
                'id' => '59',
                'parent_id' => '58',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '68',
                'rght' => '69',
            ],
            [
                'id' => '60',
                'parent_id' => '58',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '70',
                'rght' => '71',
            ],
            [
                'id' => '61',
                'parent_id' => '58',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '72',
                'rght' => '73',
            ],
            [
                'id' => '62',
                'parent_id' => '58',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '74',
                'rght' => '75',
            ],
            [
                'id' => '63',
                'parent_id' => '58',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '76',
                'rght' => '77',
            ],
            [
                'id' => '64',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Regencies',
                'lft' => '79',
                'rght' => '90',
            ],
            [
                'id' => '65',
                'parent_id' => '64',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '80',
                'rght' => '81',
            ],
            [
                'id' => '66',
                'parent_id' => '64',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '82',
                'rght' => '83',
            ],
            [
                'id' => '67',
                'parent_id' => '64',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '84',
                'rght' => '85',
            ],
            [
                'id' => '68',
                'parent_id' => '64',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '86',
                'rght' => '87',
            ],
            [
                'id' => '69',
                'parent_id' => '64',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '88',
                'rght' => '89',
            ],
            [
                'id' => '70',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'Villages',
                'lft' => '91',
                'rght' => '102',
            ],
            [
                'id' => '71',
                'parent_id' => '70',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '92',
                'rght' => '93',
            ],
            [
                'id' => '72',
                'parent_id' => '70',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '94',
                'rght' => '95',
            ],
            [
                'id' => '73',
                'parent_id' => '70',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '96',
                'rght' => '97',
            ],
            [
                'id' => '74',
                'parent_id' => '70',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '98',
                'rght' => '99',
            ],
            [
                'id' => '75',
                'parent_id' => '70',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '100',
                'rght' => '101',
            ],
            [
                'id' => '76',
                'parent_id' => '6',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'ProductCategories',
                'lft' => '103',
                'rght' => '114',
            ],
            [
                'id' => '77',
                'parent_id' => '76',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'index',
                'lft' => '104',
                'rght' => '105',
            ],
            [
                'id' => '78',
                'parent_id' => '76',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'view',
                'lft' => '106',
                'rght' => '107',
            ],
            [
                'id' => '79',
                'parent_id' => '76',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'add',
                'lft' => '108',
                'rght' => '109',
            ],
            [
                'id' => '80',
                'parent_id' => '76',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'edit',
                'lft' => '110',
                'rght' => '111',
            ],
            [
                'id' => '81',
                'parent_id' => '76',
                'model' => NULL,
                'foreign_key' => NULL,
                'alias' => 'delete',
                'lft' => '112',
                'rght' => '113',
            ],
        ];

        $table = $this->table('acos');
        $table->insert($data)->save();
    }
}
