<?php
use Migrations\AbstractSeed;

/**
 * Attributes seed.
 */
class AttributesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'parent_id' => NULL,
                'lft' => '1',
                'rght' => '8',
                'product_category_id' => '16',
                'name' => 'size',
            ],
            [
                'id' => '2',
                'parent_id' => '1',
                'lft' => '2',
                'rght' => '3',
                'product_category_id' => '16',
                'name' => 'S',
            ],
            [
                'id' => '3',
                'parent_id' => '1',
                'lft' => '4',
                'rght' => '5',
                'product_category_id' => '16',
                'name' => 'L',
            ],
            [
                'id' => '4',
                'parent_id' => '1',
                'lft' => '6',
                'rght' => '7',
                'product_category_id' => '16',
                'name' => 'XL',
            ],
            [
                'id' => '5',
                'parent_id' => NULL,
                'lft' => '9',
                'rght' => '14',
                'product_category_id' => '16',
                'name' => 'bahan',
            ],
            [
                'id' => '6',
                'parent_id' => '5',
                'lft' => '10',
                'rght' => '11',
                'product_category_id' => '16',
                'name' => 'katun',
            ],
            [
                'id' => '7',
                'parent_id' => '5',
                'lft' => '12',
                'rght' => '13',
                'product_category_id' => '16',
                'name' => 'satin',
            ],
            [
                'id' => '8',
                'parent_id' => NULL,
                'lft' => '15',
                'rght' => '26',
                'product_category_id' => '16',
                'name' => 'Material',
            ],
            [
                'id' => '9',
                'parent_id' => '8',
                'lft' => '16',
                'rght' => '17',
                'product_category_id' => '16',
                'name' => 'Karet',
            ],
            [
                'id' => '10',
                'parent_id' => '8',
                'lft' => '18',
                'rght' => '19',
                'product_category_id' => '16',
                'name' => 'Silicone',
            ],
            [
                'id' => '11',
                'parent_id' => '8',
                'lft' => '20',
                'rght' => '21',
                'product_category_id' => '16',
                'name' => 'Stainless Steel',
            ],
            [
                'id' => '12',
                'parent_id' => '8',
                'lft' => '22',
                'rght' => '23',
                'product_category_id' => '16',
                'name' => 'Others',
            ],
            [
                'id' => '13',
                'parent_id' => '8',
                'lft' => '24',
                'rght' => '25',
                'product_category_id' => '16',
                'name' => 'Not Specified',
            ],
            [
                'id' => '14',
                'parent_id' => NULL,
                'lft' => '27',
                'rght' => '30',
                'product_category_id' => '16',
                'name' => 'Comming Soon',
            ],
            [
                'id' => '15',
                'parent_id' => '14',
                'lft' => '28',
                'rght' => '29',
                'product_category_id' => '16',
                'name' => 'Comming Soon',
            ],
            [
                'id' => '16',
                'parent_id' => NULL,
                'lft' => '31',
                'rght' => '36',
                'product_category_id' => '16',
                'name' => 'Type',
            ],
            [
                'id' => '17',
                'parent_id' => '16',
                'lft' => '32',
                'rght' => '33',
                'product_category_id' => '16',
                'name' => 'Wiper Arm',
            ],
            [
                'id' => '18',
                'parent_id' => '16',
                'lft' => '34',
                'rght' => '35',
                'product_category_id' => '16',
                'name' => 'Wiper Blade',
            ],
            [
                'id' => '19',
                'parent_id' => NULL,
                'lft' => '37',
                'rght' => '46',
                'product_category_id' => '67',
                'name' => 'Ukuran',
            ],
            [
                'id' => '20',
                'parent_id' => '19',
                'lft' => '38',
                'rght' => '39',
                'product_category_id' => '67',
                'name' => 'S',
            ],
            [
                'id' => '21',
                'parent_id' => '19',
                'lft' => '40',
                'rght' => '41',
                'product_category_id' => '67',
                'name' => 'M',
            ],
            [
                'id' => '22',
                'parent_id' => '19',
                'lft' => '42',
                'rght' => '43',
                'product_category_id' => '67',
                'name' => 'L',
            ],
            [
                'id' => '23',
                'parent_id' => '19',
                'lft' => '44',
                'rght' => '45',
                'product_category_id' => '67',
                'name' => 'XL',
            ],
            [
                'id' => '24',
                'parent_id' => NULL,
                'lft' => '47',
                'rght' => '56',
                'product_category_id' => '67',
                'name' => 'Warna',
            ],
            [
                'id' => '25',
                'parent_id' => '24',
                'lft' => '48',
                'rght' => '49',
                'product_category_id' => '67',
                'name' => 'White',
            ],
            [
                'id' => '26',
                'parent_id' => '24',
                'lft' => '50',
                'rght' => '51',
                'product_category_id' => '67',
                'name' => 'Black',
            ],
            [
                'id' => '27',
                'parent_id' => '24',
                'lft' => '52',
                'rght' => '53',
                'product_category_id' => '67',
                'name' => 'Maroon',
            ],
            [
                'id' => '28',
                'parent_id' => '24',
                'lft' => '54',
                'rght' => '55',
                'product_category_id' => '67',
                'name' => 'Navy',
            ],
            [
                'id' => '29',
                'parent_id' => NULL,
                'lft' => '57',
                'rght' => '62',
                'product_category_id' => '67',
                'name' => 'Tipe',
            ],
            [
                'id' => '30',
                'parent_id' => '29',
                'lft' => '58',
                'rght' => '59',
                'product_category_id' => '67',
                'name' => 'Lengan Panjang',
            ],
            [
                'id' => '31',
                'parent_id' => '29',
                'lft' => '60',
                'rght' => '61',
                'product_category_id' => '67',
                'name' => 'Lengan Pendek',
            ],
            [
                'id' => '32',
                'parent_id' => NULL,
                'lft' => '63',
                'rght' => '66',
                'product_category_id' => '67',
                'name' => 'Bahan',
            ],
            [
                'id' => '33',
                'parent_id' => '32',
                'lft' => '64',
                'rght' => '65',
                'product_category_id' => '67',
                'name' => 'Katun',
            ],
            [
                'id' => '34',
                'parent_id' => NULL,
                'lft' => '67',
                'rght' => '82',
                'product_category_id' => '74',
                'name' => 'Ukuran',
            ],
            [
                'id' => '35',
                'parent_id' => '34',
                'lft' => '68',
                'rght' => '69',
                'product_category_id' => '74',
                'name' => '28',
            ],
            [
                'id' => '36',
                'parent_id' => '34',
                'lft' => '70',
                'rght' => '71',
                'product_category_id' => '74',
                'name' => '29',
            ],
            [
                'id' => '37',
                'parent_id' => '34',
                'lft' => '72',
                'rght' => '73',
                'product_category_id' => '74',
                'name' => '30',
            ],
            [
                'id' => '38',
                'parent_id' => '34',
                'lft' => '74',
                'rght' => '75',
                'product_category_id' => '74',
                'name' => '31',
            ],
            [
                'id' => '39',
                'parent_id' => '34',
                'lft' => '76',
                'rght' => '77',
                'product_category_id' => '74',
                'name' => '32',
            ],
            [
                'id' => '40',
                'parent_id' => '34',
                'lft' => '78',
                'rght' => '79',
                'product_category_id' => '74',
                'name' => '33',
            ],
            [
                'id' => '41',
                'parent_id' => '34',
                'lft' => '80',
                'rght' => '81',
                'product_category_id' => '74',
                'name' => '34',
            ],
            [
                'id' => '42',
                'parent_id' => NULL,
                'lft' => '83',
                'rght' => '96',
                'product_category_id' => '74',
                'name' => 'Warna',
            ],
            [
                'id' => '43',
                'parent_id' => '42',
                'lft' => '84',
                'rght' => '85',
                'product_category_id' => '74',
                'name' => 'Moka',
            ],
            [
                'id' => '44',
                'parent_id' => '42',
                'lft' => '86',
                'rght' => '87',
                'product_category_id' => '74',
                'name' => 'Khaki',
            ],
            [
                'id' => '45',
                'parent_id' => '42',
                'lft' => '88',
                'rght' => '89',
                'product_category_id' => '74',
                'name' => 'Cream',
            ],
            [
                'id' => '46',
                'parent_id' => '42',
                'lft' => '90',
                'rght' => '91',
                'product_category_id' => '74',
                'name' => 'Abu Abu',
            ],
            [
                'id' => '47',
                'parent_id' => '42',
                'lft' => '92',
                'rght' => '93',
                'product_category_id' => '74',
                'name' => 'Biru Dongker',
            ],
            [
                'id' => '48',
                'parent_id' => '42',
                'lft' => '94',
                'rght' => '95',
                'product_category_id' => '74',
                'name' => 'Hitam',
            ],
            [
                'id' => '49',
                'parent_id' => NULL,
                'lft' => '97',
                'rght' => '100',
                'product_category_id' => '74',
                'name' => 'Bahan',
            ],
            [
                'id' => '50',
                'parent_id' => '49',
                'lft' => '98',
                'rght' => '99',
                'product_category_id' => '74',
                'name' => 'Cotton Stretch',
            ],
            [
                'id' => '51',
                'parent_id' => NULL,
                'lft' => '101',
                'rght' => '126',
                'product_category_id' => '305',
                'name' => 'Ukuran',
            ],
            [
                'id' => '52',
                'parent_id' => '51',
                'lft' => '102',
                'rght' => '103',
                'product_category_id' => '305',
                'name' => '34',
            ],
            [
                'id' => '53',
                'parent_id' => '51',
                'lft' => '104',
                'rght' => '105',
                'product_category_id' => '305',
                'name' => '35',
            ],
            [
                'id' => '54',
                'parent_id' => '51',
                'lft' => '106',
                'rght' => '107',
                'product_category_id' => '305',
                'name' => '36',
            ],
            [
                'id' => '55',
                'parent_id' => '51',
                'lft' => '108',
                'rght' => '109',
                'product_category_id' => '305',
                'name' => '37',
            ],
            [
                'id' => '56',
                'parent_id' => '51',
                'lft' => '110',
                'rght' => '111',
                'product_category_id' => '305',
                'name' => '38',
            ],
            [
                'id' => '57',
                'parent_id' => '51',
                'lft' => '112',
                'rght' => '113',
                'product_category_id' => '305',
                'name' => '39',
            ],
            [
                'id' => '58',
                'parent_id' => '51',
                'lft' => '114',
                'rght' => '115',
                'product_category_id' => '305',
                'name' => '40',
            ],
            [
                'id' => '59',
                'parent_id' => '51',
                'lft' => '116',
                'rght' => '117',
                'product_category_id' => '305',
                'name' => '41',
            ],
            [
                'id' => '60',
                'parent_id' => '51',
                'lft' => '118',
                'rght' => '119',
                'product_category_id' => '305',
                'name' => '42',
            ],
            [
                'id' => '61',
                'parent_id' => '51',
                'lft' => '120',
                'rght' => '121',
                'product_category_id' => '305',
                'name' => '43',
            ],
            [
                'id' => '62',
                'parent_id' => '51',
                'lft' => '122',
                'rght' => '123',
                'product_category_id' => '305',
                'name' => '44',
            ],
            [
                'id' => '63',
                'parent_id' => '51',
                'lft' => '124',
                'rght' => '125',
                'product_category_id' => '305',
                'name' => '45',
            ],
            [
                'id' => '64',
                'parent_id' => NULL,
                'lft' => '127',
                'rght' => '144',
                'product_category_id' => '305',
                'name' => 'Warna',
            ],
            [
                'id' => '65',
                'parent_id' => '64',
                'lft' => '128',
                'rght' => '129',
                'product_category_id' => '305',
                'name' => 'Merah',
            ],
            [
                'id' => '66',
                'parent_id' => '64',
                'lft' => '130',
                'rght' => '131',
                'product_category_id' => '305',
                'name' => 'Biru',
            ],
            [
                'id' => '67',
                'parent_id' => '64',
                'lft' => '132',
                'rght' => '133',
                'product_category_id' => '305',
                'name' => 'Hijau',
            ],
            [
                'id' => '68',
                'parent_id' => '64',
                'lft' => '134',
                'rght' => '135',
                'product_category_id' => '305',
                'name' => 'Abu-Abu',
            ],
            [
                'id' => '69',
                'parent_id' => '64',
                'lft' => '136',
                'rght' => '137',
                'product_category_id' => '305',
                'name' => 'Putih',
            ],
            [
                'id' => '70',
                'parent_id' => '64',
                'lft' => '138',
                'rght' => '139',
                'product_category_id' => '305',
                'name' => 'Hitam',
            ],
            [
                'id' => '71',
                'parent_id' => '64',
                'lft' => '140',
                'rght' => '141',
                'product_category_id' => '305',
                'name' => 'Kuning',
            ],
            [
                'id' => '72',
                'parent_id' => NULL,
                'lft' => '145',
                'rght' => '154',
                'product_category_id' => '92',
                'name' => 'Ukuran',
            ],
            [
                'id' => '73',
                'parent_id' => '72',
                'lft' => '146',
                'rght' => '147',
                'product_category_id' => '92',
                'name' => 'S',
            ],
            [
                'id' => '74',
                'parent_id' => '72',
                'lft' => '148',
                'rght' => '149',
                'product_category_id' => '92',
                'name' => 'M',
            ],
            [
                'id' => '75',
                'parent_id' => '72',
                'lft' => '150',
                'rght' => '151',
                'product_category_id' => '92',
                'name' => 'L',
            ],
            [
                'id' => '76',
                'parent_id' => '72',
                'lft' => '152',
                'rght' => '153',
                'product_category_id' => '92',
                'name' => 'XL',
            ],
            [
                'id' => '77',
                'parent_id' => NULL,
                'lft' => '155',
                'rght' => '168',
                'product_category_id' => '92',
                'name' => 'Warna',
            ],
            [
                'id' => '78',
                'parent_id' => '77',
                'lft' => '156',
                'rght' => '157',
                'product_category_id' => '92',
                'name' => 'Putih',
            ],
            [
                'id' => '79',
                'parent_id' => '77',
                'lft' => '158',
                'rght' => '159',
                'product_category_id' => '92',
                'name' => 'Biru Muda',
            ],
            [
                'id' => '80',
                'parent_id' => '77',
                'lft' => '160',
                'rght' => '161',
                'product_category_id' => '92',
                'name' => 'Coklat',
            ],
            [
                'id' => '81',
                'parent_id' => NULL,
                'lft' => '169',
                'rght' => '186',
                'product_category_id' => '43',
                'name' => 'Ukuran',
            ],
            [
                'id' => '82',
                'parent_id' => '81',
                'lft' => '170',
                'rght' => '171',
                'product_category_id' => '43',
                'name' => '34',
            ],
            [
                'id' => '83',
                'parent_id' => '81',
                'lft' => '172',
                'rght' => '173',
                'product_category_id' => '43',
                'name' => '35',
            ],
            [
                'id' => '84',
                'parent_id' => '81',
                'lft' => '174',
                'rght' => '175',
                'product_category_id' => '43',
                'name' => '36',
            ],
            [
                'id' => '85',
                'parent_id' => '81',
                'lft' => '176',
                'rght' => '177',
                'product_category_id' => '43',
                'name' => '37',
            ],
            [
                'id' => '86',
                'parent_id' => '81',
                'lft' => '178',
                'rght' => '179',
                'product_category_id' => '43',
                'name' => '38',
            ],
            [
                'id' => '87',
                'parent_id' => '81',
                'lft' => '180',
                'rght' => '181',
                'product_category_id' => '43',
                'name' => '39',
            ],
            [
                'id' => '88',
                'parent_id' => '81',
                'lft' => '182',
                'rght' => '183',
                'product_category_id' => '43',
                'name' => '40',
            ],
            [
                'id' => '89',
                'parent_id' => '81',
                'lft' => '184',
                'rght' => '185',
                'product_category_id' => '43',
                'name' => '41',
            ],
            [
                'id' => '90',
                'parent_id' => NULL,
                'lft' => '187',
                'rght' => '198',
                'product_category_id' => '43',
                'name' => 'Warna',
            ],
            [
                'id' => '91',
                'parent_id' => '90',
                'lft' => '188',
                'rght' => '189',
                'product_category_id' => '43',
                'name' => 'Putih',
            ],
            [
                'id' => '92',
                'parent_id' => '90',
                'lft' => '190',
                'rght' => '191',
                'product_category_id' => '43',
                'name' => 'Hitam',
            ],
            [
                'id' => '93',
                'parent_id' => '90',
                'lft' => '192',
                'rght' => '193',
                'product_category_id' => '43',
                'name' => 'Kuning',
            ],
            [
                'id' => '94',
                'parent_id' => '90',
                'lft' => '194',
                'rght' => '195',
                'product_category_id' => '43',
                'name' => 'Abu-Abu',
            ],
            [
                'id' => '95',
                'parent_id' => '90',
                'lft' => '196',
                'rght' => '197',
                'product_category_id' => '43',
                'name' => 'Merah',
            ],
            [
                'id' => '96',
                'parent_id' => '77',
                'lft' => '162',
                'rght' => '163',
                'product_category_id' => '92',
                'name' => 'merah',
            ],
            [
                'id' => '97',
                'parent_id' => '77',
                'lft' => '164',
                'rght' => '165',
                'product_category_id' => '92',
                'name' => 'hitam',
            ],
            [
                'id' => '98',
                'parent_id' => '77',
                'lft' => '166',
                'rght' => '167',
                'product_category_id' => '92',
                'name' => 'biru',
            ],
            [
                'id' => '110',
                'parent_id' => NULL,
                'lft' => '199',
                'rght' => '206',
                'product_category_id' => '56',
                'name' => 'Warna',
            ],
            [
                'id' => '111',
                'parent_id' => '110',
                'lft' => '200',
                'rght' => '201',
                'product_category_id' => '56',
                'name' => 'Coklat',
            ],
            [
                'id' => '112',
                'parent_id' => '110',
                'lft' => '202',
                'rght' => '203',
                'product_category_id' => '56',
                'name' => 'Ungu',
            ],
            [
                'id' => '113',
                'parent_id' => '110',
                'lft' => '204',
                'rght' => '205',
                'product_category_id' => '56',
                'name' => 'Motif Bunga',
            ],
            [
                'id' => '114',
                'parent_id' => NULL,
                'lft' => '207',
                'rght' => '214',
                'product_category_id' => '401',
                'name' => 'WARNA',
            ],
            [
                'id' => '115',
                'parent_id' => '114',
                'lft' => '208',
                'rght' => '209',
                'product_category_id' => '401',
                'name' => 'GOLD',
            ],
            [
                'id' => '116',
                'parent_id' => '114',
                'lft' => '210',
                'rght' => '211',
                'product_category_id' => '401',
                'name' => 'HITAM',
            ],
            [
                'id' => '117',
                'parent_id' => '114',
                'lft' => '212',
                'rght' => '213',
                'product_category_id' => '401',
                'name' => 'SILVER',
            ],
            [
                'id' => '118',
                'parent_id' => NULL,
                'lft' => '215',
                'rght' => '222',
                'product_category_id' => '408',
                'name' => 'WARNA',
            ],
            [
                'id' => '119',
                'parent_id' => '118',
                'lft' => '216',
                'rght' => '217',
                'product_category_id' => '408',
                'name' => 'MERAH',
            ],
            [
                'id' => '120',
                'parent_id' => '118',
                'lft' => '218',
                'rght' => '219',
                'product_category_id' => '408',
                'name' => 'HITAM',
            ],
            [
                'id' => '121',
                'parent_id' => '118',
                'lft' => '220',
                'rght' => '221',
                'product_category_id' => '408',
                'name' => 'BIRU',
            ],
            [
                'id' => '126',
                'parent_id' => '64',
                'lft' => '142',
                'rght' => '143',
                'product_category_id' => '305',
                'name' => 'Ungu',
            ],
            [
                'id' => '127',
                'parent_id' => NULL,
                'lft' => '223',
                'rght' => '234',
                'product_category_id' => '94',
                'name' => 'ukuran',
            ],
            [
                'id' => '128',
                'parent_id' => '127',
                'lft' => '224',
                'rght' => '225',
                'product_category_id' => '94',
                'name' => 's',
            ],
            [
                'id' => '129',
                'parent_id' => '127',
                'lft' => '226',
                'rght' => '227',
                'product_category_id' => '94',
                'name' => 'm',
            ],
            [
                'id' => '130',
                'parent_id' => '127',
                'lft' => '228',
                'rght' => '229',
                'product_category_id' => '94',
                'name' => 'l',
            ],
            [
                'id' => '131',
                'parent_id' => '127',
                'lft' => '230',
                'rght' => '231',
                'product_category_id' => '94',
                'name' => 'xl',
            ],
            [
                'id' => '132',
                'parent_id' => '127',
                'lft' => '232',
                'rght' => '233',
                'product_category_id' => '94',
                'name' => 'xxl',
            ],
            [
                'id' => '133',
                'parent_id' => NULL,
                'lft' => '235',
                'rght' => '246',
                'product_category_id' => '89',
                'name' => 'UKURAN',
            ],
            [
                'id' => '134',
                'parent_id' => '133',
                'lft' => '236',
                'rght' => '237',
                'product_category_id' => '89',
                'name' => 'S',
            ],
            [
                'id' => '135',
                'parent_id' => '133',
                'lft' => '238',
                'rght' => '239',
                'product_category_id' => '89',
                'name' => 'M',
            ],
            [
                'id' => '136',
                'parent_id' => '133',
                'lft' => '240',
                'rght' => '241',
                'product_category_id' => '89',
                'name' => 'L',
            ],
            [
                'id' => '137',
                'parent_id' => '133',
                'lft' => '242',
                'rght' => '243',
                'product_category_id' => '89',
                'name' => 'XL',
            ],
            [
                'id' => '138',
                'parent_id' => '133',
                'lft' => '244',
                'rght' => '245',
                'product_category_id' => '89',
                'name' => 'XXL',
            ],
            [
                'id' => '139',
                'parent_id' => NULL,
                'lft' => '247',
                'rght' => '254',
                'product_category_id' => '76',
                'name' => 'WARNA',
            ],
            [
                'id' => '140',
                'parent_id' => '139',
                'lft' => '248',
                'rght' => '249',
                'product_category_id' => '76',
                'name' => 'GREY',
            ],
            [
                'id' => '141',
                'parent_id' => '139',
                'lft' => '250',
                'rght' => '251',
                'product_category_id' => '76',
                'name' => 'HITAM',
            ],
            [
                'id' => '142',
                'parent_id' => '139',
                'lft' => '252',
                'rght' => '253',
                'product_category_id' => '76',
                'name' => 'NAVYBLUE',
            ],
            [
                'id' => '143',
                'parent_id' => NULL,
                'lft' => '255',
                'rght' => '270',
                'product_category_id' => '76',
                'name' => 'UKURAN',
            ],
            [
                'id' => '144',
                'parent_id' => '143',
                'lft' => '256',
                'rght' => '257',
                'product_category_id' => '76',
                'name' => '28',
            ],
            [
                'id' => '145',
                'parent_id' => '143',
                'lft' => '258',
                'rght' => '259',
                'product_category_id' => '76',
                'name' => '29',
            ],
            [
                'id' => '146',
                'parent_id' => '143',
                'lft' => '260',
                'rght' => '261',
                'product_category_id' => '76',
                'name' => '30',
            ],
            [
                'id' => '147',
                'parent_id' => '143',
                'lft' => '262',
                'rght' => '263',
                'product_category_id' => '76',
                'name' => '31',
            ],
            [
                'id' => '148',
                'parent_id' => '143',
                'lft' => '264',
                'rght' => '265',
                'product_category_id' => '76',
                'name' => '32',
            ],
            [
                'id' => '149',
                'parent_id' => '143',
                'lft' => '266',
                'rght' => '267',
                'product_category_id' => '76',
                'name' => '33',
            ],
            [
                'id' => '150',
                'parent_id' => '143',
                'lft' => '268',
                'rght' => '269',
                'product_category_id' => '76',
                'name' => '34',
            ],
            [
                'id' => '151',
                'parent_id' => NULL,
                'lft' => '271',
                'rght' => '286',
                'product_category_id' => '17',
                'name' => 'Warna',
            ],
            [
                'id' => '152',
                'parent_id' => '151',
                'lft' => '272',
                'rght' => '273',
                'product_category_id' => '17',
                'name' => 'Pink',
            ],
            [
                'id' => '153',
                'parent_id' => '151',
                'lft' => '274',
                'rght' => '275',
                'product_category_id' => '17',
                'name' => 'Ungu',
            ],
            [
                'id' => '154',
                'parent_id' => '151',
                'lft' => '276',
                'rght' => '277',
                'product_category_id' => '17',
                'name' => 'Merah',
            ],
            [
                'id' => '155',
                'parent_id' => '151',
                'lft' => '278',
                'rght' => '279',
                'product_category_id' => '17',
                'name' => 'Kuning',
            ],
            [
                'id' => '156',
                'parent_id' => NULL,
                'lft' => '287',
                'rght' => '296',
                'product_category_id' => '17',
                'name' => 'Ukuran',
            ],
            [
                'id' => '157',
                'parent_id' => '156',
                'lft' => '288',
                'rght' => '289',
                'product_category_id' => '17',
                'name' => 'S',
            ],
            [
                'id' => '158',
                'parent_id' => '156',
                'lft' => '290',
                'rght' => '291',
                'product_category_id' => '17',
                'name' => 'M',
            ],
            [
                'id' => '159',
                'parent_id' => '156',
                'lft' => '292',
                'rght' => '293',
                'product_category_id' => '17',
                'name' => 'L',
            ],
            [
                'id' => '160',
                'parent_id' => '156',
                'lft' => '294',
                'rght' => '295',
                'product_category_id' => '17',
                'name' => 'XL',
            ],
            [
                'id' => '161',
                'parent_id' => NULL,
                'lft' => '297',
                'rght' => '304',
                'product_category_id' => '317',
                'name' => 'WARNA',
            ],
            [
                'id' => '162',
                'parent_id' => '161',
                'lft' => '298',
                'rght' => '299',
                'product_category_id' => '317',
                'name' => 'MERAH',
            ],
            [
                'id' => '163',
                'parent_id' => '161',
                'lft' => '300',
                'rght' => '301',
                'product_category_id' => '317',
                'name' => 'BIRU',
            ],
            [
                'id' => '164',
                'parent_id' => '161',
                'lft' => '302',
                'rght' => '303',
                'product_category_id' => '317',
                'name' => 'HITAM',
            ],
            [
                'id' => '165',
                'parent_id' => NULL,
                'lft' => '305',
                'rght' => '312',
                'product_category_id' => '317',
                'name' => 'UKURAN',
            ],
            [
                'id' => '166',
                'parent_id' => '165',
                'lft' => '306',
                'rght' => '307',
                'product_category_id' => '317',
                'name' => 'S',
            ],
            [
                'id' => '167',
                'parent_id' => '165',
                'lft' => '308',
                'rght' => '309',
                'product_category_id' => '317',
                'name' => 'M',
            ],
            [
                'id' => '168',
                'parent_id' => '165',
                'lft' => '310',
                'rght' => '311',
                'product_category_id' => '317',
                'name' => 'L',
            ],
            [
                'id' => '169',
                'parent_id' => NULL,
                'lft' => '313',
                'rght' => '324',
                'product_category_id' => '431',
                'name' => 'Warna',
            ],
            [
                'id' => '170',
                'parent_id' => '169',
                'lft' => '314',
                'rght' => '315',
                'product_category_id' => '431',
                'name' => 'Merah',
            ],
            [
                'id' => '171',
                'parent_id' => '169',
                'lft' => '316',
                'rght' => '317',
                'product_category_id' => '431',
                'name' => 'Biru',
            ],
            [
                'id' => '172',
                'parent_id' => '169',
                'lft' => '318',
                'rght' => '319',
                'product_category_id' => '431',
                'name' => 'Hitam',
            ],
            [
                'id' => '173',
                'parent_id' => '169',
                'lft' => '320',
                'rght' => '321',
                'product_category_id' => '431',
                'name' => 'Abu Abu',
            ],
            [
                'id' => '174',
                'parent_id' => '169',
                'lft' => '322',
                'rght' => '323',
                'product_category_id' => '431',
                'name' => 'Ungu',
            ],
            [
                'id' => '175',
                'parent_id' => NULL,
                'lft' => '325',
                'rght' => '334',
                'product_category_id' => '213',
                'name' => 'UKURAN',
            ],
            [
                'id' => '176',
                'parent_id' => '175',
                'lft' => '326',
                'rght' => '327',
                'product_category_id' => '213',
                'name' => 'S',
            ],
            [
                'id' => '177',
                'parent_id' => '175',
                'lft' => '328',
                'rght' => '329',
                'product_category_id' => '213',
                'name' => 'M',
            ],
            [
                'id' => '178',
                'parent_id' => '175',
                'lft' => '330',
                'rght' => '331',
                'product_category_id' => '213',
                'name' => 'L',
            ],
            [
                'id' => '179',
                'parent_id' => '175',
                'lft' => '332',
                'rght' => '333',
                'product_category_id' => '213',
                'name' => 'XL',
            ],
            [
                'id' => '180',
                'parent_id' => NULL,
                'lft' => '335',
                'rght' => '344',
                'product_category_id' => '239',
                'name' => 'Warna',
            ],
            [
                'id' => '181',
                'parent_id' => '180',
                'lft' => '336',
                'rght' => '337',
                'product_category_id' => '239',
                'name' => 'Merah',
            ],
            [
                'id' => '182',
                'parent_id' => '180',
                'lft' => '338',
                'rght' => '339',
                'product_category_id' => '239',
                'name' => 'Biru',
            ],
            [
                'id' => '183',
                'parent_id' => '180',
                'lft' => '340',
                'rght' => '341',
                'product_category_id' => '239',
                'name' => 'Hitam',
            ],
            [
                'id' => '184',
                'parent_id' => NULL,
                'lft' => '345',
                'rght' => '352',
                'product_category_id' => '239',
                'name' => 'Motif',
            ],
            [
                'id' => '185',
                'parent_id' => '184',
                'lft' => '346',
                'rght' => '347',
                'product_category_id' => '239',
                'name' => 'Not Specified',
            ],
            [
                'id' => '186',
                'parent_id' => '184',
                'lft' => '348',
                'rght' => '349',
                'product_category_id' => '239',
                'name' => 'Captain America',
            ],
            [
                'id' => '187',
                'parent_id' => '184',
                'lft' => '350',
                'rght' => '351',
                'product_category_id' => '239',
                'name' => 'Spiderman',
            ],
            [
                'id' => '188',
                'parent_id' => '180',
                'lft' => '342',
                'rght' => '343',
                'product_category_id' => '239',
                'name' => 'Not Specified',
            ],
            [
                'id' => '189',
                'parent_id' => NULL,
                'lft' => '353',
                'rght' => '362',
                'product_category_id' => '126',
                'name' => 'Warna',
            ],
            [
                'id' => '190',
                'parent_id' => '189',
                'lft' => '354',
                'rght' => '355',
                'product_category_id' => '126',
                'name' => 'Merah',
            ],
            [
                'id' => '191',
                'parent_id' => '189',
                'lft' => '356',
                'rght' => '357',
                'product_category_id' => '126',
                'name' => 'Biru',
            ],
            [
                'id' => '192',
                'parent_id' => '189',
                'lft' => '358',
                'rght' => '359',
                'product_category_id' => '126',
                'name' => 'Ungu',
            ],
            [
                'id' => '193',
                'parent_id' => '189',
                'lft' => '360',
                'rght' => '361',
                'product_category_id' => '126',
                'name' => 'Hijau',
            ],
            [
                'id' => '194',
                'parent_id' => NULL,
                'lft' => '363',
                'rght' => '378',
                'product_category_id' => '43',
                'name' => 'UKURAN',
            ],
            [
                'id' => '195',
                'parent_id' => '194',
                'lft' => '364',
                'rght' => '365',
                'product_category_id' => '43',
                'name' => '36',
            ],
            [
                'id' => '196',
                'parent_id' => '194',
                'lft' => '366',
                'rght' => '367',
                'product_category_id' => '43',
                'name' => '37',
            ],
            [
                'id' => '197',
                'parent_id' => '194',
                'lft' => '368',
                'rght' => '369',
                'product_category_id' => '43',
                'name' => '38',
            ],
            [
                'id' => '198',
                'parent_id' => '194',
                'lft' => '370',
                'rght' => '371',
                'product_category_id' => '43',
                'name' => '39',
            ],
            [
                'id' => '199',
                'parent_id' => '194',
                'lft' => '372',
                'rght' => '373',
                'product_category_id' => '43',
                'name' => '40',
            ],
            [
                'id' => '200',
                'parent_id' => '194',
                'lft' => '374',
                'rght' => '375',
                'product_category_id' => '43',
                'name' => '41',
            ],
            [
                'id' => '201',
                'parent_id' => '194',
                'lft' => '376',
                'rght' => '377',
                'product_category_id' => '43',
                'name' => '42',
            ],
            [
                'id' => '202',
                'parent_id' => NULL,
                'lft' => '379',
                'rght' => '390',
                'product_category_id' => '150',
                'name' => 'Warna',
            ],
            [
                'id' => '203',
                'parent_id' => '202',
                'lft' => '380',
                'rght' => '381',
                'product_category_id' => '150',
                'name' => 'Putih',
            ],
            [
                'id' => '204',
                'parent_id' => '202',
                'lft' => '382',
                'rght' => '383',
                'product_category_id' => '150',
                'name' => 'Kuning',
            ],
            [
                'id' => '205',
                'parent_id' => '202',
                'lft' => '384',
                'rght' => '385',
                'product_category_id' => '150',
                'name' => 'Hijau',
            ],
            [
                'id' => '206',
                'parent_id' => '202',
                'lft' => '386',
                'rght' => '387',
                'product_category_id' => '150',
                'name' => 'Biru',
            ],
            [
                'id' => '207',
                'parent_id' => '202',
                'lft' => '388',
                'rght' => '389',
                'product_category_id' => '150',
                'name' => 'Merah',
            ],
            [
                'id' => '208',
                'parent_id' => NULL,
                'lft' => '391',
                'rght' => '400',
                'product_category_id' => '432',
                'name' => 'Warna',
            ],
            [
                'id' => '209',
                'parent_id' => '208',
                'lft' => '392',
                'rght' => '393',
                'product_category_id' => '432',
                'name' => 'Hitam',
            ],
            [
                'id' => '210',
                'parent_id' => '208',
                'lft' => '394',
                'rght' => '395',
                'product_category_id' => '432',
                'name' => 'Putih',
            ],
            [
                'id' => '211',
                'parent_id' => '208',
                'lft' => '396',
                'rght' => '397',
                'product_category_id' => '432',
                'name' => 'Biru',
            ],
            [
                'id' => '212',
                'parent_id' => '208',
                'lft' => '398',
                'rght' => '399',
                'product_category_id' => '432',
                'name' => 'Merah',
            ],
            [
                'id' => '213',
                'parent_id' => '151',
                'lft' => '280',
                'rght' => '281',
                'product_category_id' => '17',
                'name' => 'Hitam',
            ],
            [
                'id' => '214',
                'parent_id' => '151',
                'lft' => '282',
                'rght' => '283',
                'product_category_id' => '17',
                'name' => 'Gray',
            ],
            [
                'id' => '215',
                'parent_id' => '151',
                'lft' => '284',
                'rght' => '285',
                'product_category_id' => '17',
                'name' => 'Coklat',
            ],
            [
                'id' => '216',
                'parent_id' => NULL,
                'lft' => '401',
                'rght' => '416',
                'product_category_id' => '303',
                'name' => 'Warna',
            ],
            [
                'id' => '217',
                'parent_id' => '216',
                'lft' => '402',
                'rght' => '403',
                'product_category_id' => '303',
                'name' => 'Merah-Biru',
            ],
            [
                'id' => '218',
                'parent_id' => '216',
                'lft' => '404',
                'rght' => '405',
                'product_category_id' => '303',
                'name' => 'Kuning-Biru',
            ],
            [
                'id' => '219',
                'parent_id' => '216',
                'lft' => '406',
                'rght' => '407',
                'product_category_id' => '303',
                'name' => 'Merah-hitam',
            ],
            [
                'id' => '220',
                'parent_id' => '216',
                'lft' => '408',
                'rght' => '409',
                'product_category_id' => '303',
                'name' => 'Biru-Kuning',
            ],
            [
                'id' => '221',
                'parent_id' => '216',
                'lft' => '410',
                'rght' => '411',
                'product_category_id' => '303',
                'name' => 'Biru-hijau',
            ],
            [
                'id' => '222',
                'parent_id' => '216',
                'lft' => '412',
                'rght' => '413',
                'product_category_id' => '303',
                'name' => 'Merah',
            ],
            [
                'id' => '223',
                'parent_id' => '216',
                'lft' => '414',
                'rght' => '415',
                'product_category_id' => '303',
                'name' => 'Biru',
            ],
            [
                'id' => '224',
                'parent_id' => NULL,
                'lft' => '417',
                'rght' => '424',
                'product_category_id' => '435',
                'name' => 'Warna',
            ],
            [
                'id' => '225',
                'parent_id' => '224',
                'lft' => '418',
                'rght' => '419',
                'product_category_id' => '435',
                'name' => 'Putih',
            ],
            [
                'id' => '226',
                'parent_id' => '224',
                'lft' => '420',
                'rght' => '421',
                'product_category_id' => '435',
                'name' => 'Hitam',
            ],
            [
                'id' => '227',
                'parent_id' => '224',
                'lft' => '422',
                'rght' => '423',
                'product_category_id' => '435',
                'name' => 'Biru',
            ],
            [
                'id' => '228',
                'parent_id' => NULL,
                'lft' => '425',
                'rght' => '432',
                'product_category_id' => '311',
                'name' => 'WARNA',
            ],
            [
                'id' => '229',
                'parent_id' => '228',
                'lft' => '426',
                'rght' => '427',
                'product_category_id' => '311',
                'name' => 'MERAH',
            ],
            [
                'id' => '230',
                'parent_id' => '228',
                'lft' => '428',
                'rght' => '429',
                'product_category_id' => '311',
                'name' => 'HITAM',
            ],
            [
                'id' => '231',
                'parent_id' => '228',
                'lft' => '430',
                'rght' => '431',
                'product_category_id' => '311',
                'name' => 'BIRU',
            ],
            [
                'id' => '232',
                'parent_id' => NULL,
                'lft' => '433',
                'rght' => '442',
                'product_category_id' => '446',
                'name' => 'Warna',
            ],
            [
                'id' => '233',
                'parent_id' => '232',
                'lft' => '434',
                'rght' => '435',
                'product_category_id' => '446',
                'name' => 'Merah',
            ],
            [
                'id' => '234',
                'parent_id' => '232',
                'lft' => '436',
                'rght' => '437',
                'product_category_id' => '446',
                'name' => 'Abu Abu',
            ],
            [
                'id' => '235',
                'parent_id' => '232',
                'lft' => '438',
                'rght' => '439',
                'product_category_id' => '446',
                'name' => 'Biru',
            ],
            [
                'id' => '236',
                'parent_id' => '232',
                'lft' => '440',
                'rght' => '441',
                'product_category_id' => '446',
                'name' => 'Hitam',
            ],
            [
                'id' => '237',
                'parent_id' => NULL,
                'lft' => '443',
                'rght' => '454',
                'product_category_id' => '404',
                'name' => 'Warna',
            ],
            [
                'id' => '238',
                'parent_id' => '237',
                'lft' => '444',
                'rght' => '445',
                'product_category_id' => '404',
                'name' => 'Putih',
            ],
            [
                'id' => '239',
                'parent_id' => '237',
                'lft' => '446',
                'rght' => '447',
                'product_category_id' => '404',
                'name' => 'Hitam',
            ],
            [
                'id' => '240',
                'parent_id' => '237',
                'lft' => '448',
                'rght' => '449',
                'product_category_id' => '404',
                'name' => 'Biru',
            ],
            [
                'id' => '241',
                'parent_id' => '237',
                'lft' => '450',
                'rght' => '451',
                'product_category_id' => '404',
                'name' => 'Kuning',
            ],
            [
                'id' => '242',
                'parent_id' => '237',
                'lft' => '452',
                'rght' => '453',
                'product_category_id' => '404',
                'name' => 'Merah',
            ],
            [
                'id' => '243',
                'parent_id' => NULL,
                'lft' => '455',
                'rght' => '464',
                'product_category_id' => '70',
                'name' => 'ukuran',
            ],
            [
                'id' => '244',
                'parent_id' => '243',
                'lft' => '456',
                'rght' => '457',
                'product_category_id' => '70',
                'name' => 'S',
            ],
            [
                'id' => '245',
                'parent_id' => '243',
                'lft' => '458',
                'rght' => '459',
                'product_category_id' => '70',
                'name' => 'M',
            ],
            [
                'id' => '246',
                'parent_id' => '243',
                'lft' => '460',
                'rght' => '461',
                'product_category_id' => '70',
                'name' => 'L',
            ],
            [
                'id' => '247',
                'parent_id' => '243',
                'lft' => '462',
                'rght' => '463',
                'product_category_id' => '70',
                'name' => 'XL',
            ],
            [
                'id' => '248',
                'parent_id' => NULL,
                'lft' => '465',
                'rght' => '470',
                'product_category_id' => '70',
                'name' => 'WARNA',
            ],
            [
                'id' => '249',
                'parent_id' => '248',
                'lft' => '466',
                'rght' => '467',
                'product_category_id' => '70',
                'name' => 'HITAM',
            ],
            [
                'id' => '250',
                'parent_id' => '248',
                'lft' => '468',
                'rght' => '469',
                'product_category_id' => '70',
                'name' => 'GRAY',
            ],
            [
                'id' => '251',
                'parent_id' => NULL,
                'lft' => '471',
                'rght' => '484',
                'product_category_id' => '105',
                'name' => 'Warna',
            ],
            [
                'id' => '252',
                'parent_id' => '251',
                'lft' => '472',
                'rght' => '473',
                'product_category_id' => '105',
                'name' => 'Ungu',
            ],
            [
                'id' => '253',
                'parent_id' => '251',
                'lft' => '474',
                'rght' => '475',
                'product_category_id' => '105',
                'name' => 'Putih',
            ],
            [
                'id' => '254',
                'parent_id' => '251',
                'lft' => '476',
                'rght' => '477',
                'product_category_id' => '105',
                'name' => 'Merah',
            ],
            [
                'id' => '255',
                'parent_id' => '251',
                'lft' => '478',
                'rght' => '479',
                'product_category_id' => '105',
                'name' => 'Kuning',
            ],
            [
                'id' => '256',
                'parent_id' => '251',
                'lft' => '480',
                'rght' => '481',
                'product_category_id' => '105',
                'name' => 'Biru',
            ],
            [
                'id' => '257',
                'parent_id' => '251',
                'lft' => '482',
                'rght' => '483',
                'product_category_id' => '105',
                'name' => 'Pink',
            ],
            [
                'id' => '258',
                'parent_id' => NULL,
                'lft' => '485',
                'rght' => '492',
                'product_category_id' => '104',
                'name' => 'WARNA',
            ],
            [
                'id' => '259',
                'parent_id' => '258',
                'lft' => '486',
                'rght' => '487',
                'product_category_id' => '104',
                'name' => 'BIRU',
            ],
            [
                'id' => '260',
                'parent_id' => '258',
                'lft' => '488',
                'rght' => '489',
                'product_category_id' => '104',
                'name' => 'MERAH',
            ],
            [
                'id' => '261',
                'parent_id' => '258',
                'lft' => '490',
                'rght' => '491',
                'product_category_id' => '104',
                'name' => 'PINK',
            ],
            [
                'id' => '262',
                'parent_id' => NULL,
                'lft' => '493',
                'rght' => '502',
                'product_category_id' => '114',
                'name' => 'WARNA',
            ],
            [
                'id' => '263',
                'parent_id' => '262',
                'lft' => '494',
                'rght' => '495',
                'product_category_id' => '114',
                'name' => 'HIJAU',
            ],
            [
                'id' => '264',
                'parent_id' => '262',
                'lft' => '496',
                'rght' => '497',
                'product_category_id' => '114',
                'name' => 'PINK',
            ],
            [
                'id' => '265',
                'parent_id' => '262',
                'lft' => '498',
                'rght' => '499',
                'product_category_id' => '114',
                'name' => 'GRAY',
            ],
            [
                'id' => '266',
                'parent_id' => '262',
                'lft' => '500',
                'rght' => '501',
                'product_category_id' => '114',
                'name' => 'COKLAT',
            ],
            [
                'id' => '267',
                'parent_id' => NULL,
                'lft' => '503',
                'rght' => '510',
                'product_category_id' => '148',
                'name' => 'WARNA',
            ],
            [
                'id' => '268',
                'parent_id' => '267',
                'lft' => '504',
                'rght' => '505',
                'product_category_id' => '148',
                'name' => 'HITAM',
            ],
            [
                'id' => '269',
                'parent_id' => '267',
                'lft' => '506',
                'rght' => '507',
                'product_category_id' => '148',
                'name' => 'BIRU',
            ],
            [
                'id' => '270',
                'parent_id' => '267',
                'lft' => '508',
                'rght' => '509',
                'product_category_id' => '148',
                'name' => 'HIJAU',
            ],
        ];

        $table = $this->table('attributes');
        $table->insert($data)->save();
    }
}
