<?php
use Migrations\AbstractSeed;

/**
 * Brands seed.
 */
class BrandsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'product_category_id' => '16',
                'parent_id' => NULL,
                'lft' => '1',
                'rght' => '2',
                'name' => 'Brand Z',
            ],
            [
                'id' => '2',
                'product_category_id' => '16',
                'parent_id' => NULL,
                'lft' => '3',
                'rght' => '4',
                'name' => 'zalia',
            ],
            [
                'id' => '7',
                'product_category_id' => '500',
                'parent_id' => NULL,
                'lft' => '5',
                'rght' => '6',
                'name' => 'Eiger',
            ],
            [
                'id' => '8',
                'product_category_id' => '500',
                'parent_id' => NULL,
                'lft' => '7',
                'rght' => '8',
                'name' => 'Carvil',
            ],
            [
                'id' => '9',
                'product_category_id' => '56',
                'parent_id' => NULL,
                'lft' => '9',
                'rght' => '10',
                'name' => 'Rabbani',
            ],
            [
                'id' => '10',
                'product_category_id' => '56',
                'parent_id' => NULL,
                'lft' => '11',
                'rght' => '12',
                'name' => 'Zoya',
            ],
            [
                'id' => '11',
                'product_category_id' => '56',
                'parent_id' => NULL,
                'lft' => '13',
                'rght' => '14',
                'name' => 'Shafira',
            ],
            [
                'id' => '12',
                'product_category_id' => '502',
                'parent_id' => NULL,
                'lft' => '15',
                'rght' => '16',
                'name' => 'Adidas',
            ],
            [
                'id' => '13',
                'product_category_id' => '502',
                'parent_id' => NULL,
                'lft' => '17',
                'rght' => '18',
                'name' => 'Puma',
            ],
            [
                'id' => '14',
                'product_category_id' => '502',
                'parent_id' => NULL,
                'lft' => '19',
                'rght' => '20',
                'name' => 'Nike',
            ],
            [
                'id' => '15',
                'product_category_id' => '502',
                'parent_id' => NULL,
                'lft' => '21',
                'rght' => '22',
                'name' => 'Vans',
            ],
            [
                'id' => '16',
                'product_category_id' => '502',
                'parent_id' => NULL,
                'lft' => '23',
                'rght' => '24',
                'name' => 'Converse',
            ],
            [
                'id' => '17',
                'product_category_id' => '43',
                'parent_id' => NULL,
                'lft' => '25',
                'rght' => '26',
                'name' => 'Adidas',
            ],
            [
                'id' => '18',
                'product_category_id' => '67',
                'parent_id' => NULL,
                'lft' => '27',
                'rght' => '28',
                'name' => 'Cardinal',
            ],
            [
                'id' => '19',
                'product_category_id' => '67',
                'parent_id' => NULL,
                'lft' => '29',
                'rght' => '30',
                'name' => 'Giordano',
            ],
            [
                'id' => '20',
                'product_category_id' => '67',
                'parent_id' => NULL,
                'lft' => '31',
                'rght' => '32',
                'name' => 'Uniqlo',
            ],
            [
                'id' => '21',
                'product_category_id' => '67',
                'parent_id' => NULL,
                'lft' => '33',
                'rght' => '34',
                'name' => 'Zara',
            ],
            [
                'id' => '22',
                'product_category_id' => '92',
                'parent_id' => NULL,
                'lft' => '35',
                'rght' => '36',
                'name' => 'Rabbani',
            ],
            [
                'id' => '23',
                'product_category_id' => '92',
                'parent_id' => NULL,
                'lft' => '37',
                'rght' => '38',
                'name' => 'Elzatta',
            ],
            [
                'id' => '24',
                'product_category_id' => '92',
                'parent_id' => NULL,
                'lft' => '39',
                'rght' => '40',
                'name' => 'Samase',
            ],
            [
                'id' => '25',
                'product_category_id' => '72',
                'parent_id' => NULL,
                'lft' => '41',
                'rght' => '42',
                'name' => 'Levi\'s',
            ],
            [
                'id' => '26',
                'product_category_id' => '72',
                'parent_id' => NULL,
                'lft' => '43',
                'rght' => '44',
                'name' => 'Wrangler',
            ],
            [
                'id' => '27',
                'product_category_id' => '72',
                'parent_id' => NULL,
                'lft' => '45',
                'rght' => '46',
                'name' => 'Lea',
            ],
            [
                'id' => '28',
                'product_category_id' => '94',
                'parent_id' => NULL,
                'lft' => '47',
                'rght' => '48',
                'name' => 'Bateeq',
            ],
            [
                'id' => '29',
                'product_category_id' => '94',
                'parent_id' => NULL,
                'lft' => '49',
                'rght' => '50',
                'name' => 'Alleira',
            ],
            [
                'id' => '31',
                'product_category_id' => '74',
                'parent_id' => NULL,
                'lft' => '51',
                'rght' => '52',
                'name' => 'Uniqlo',
            ],
            [
                'id' => '32',
                'product_category_id' => '92',
                'parent_id' => NULL,
                'lft' => '53',
                'rght' => '54',
                'name' => 'FAIHA',
            ],
            [
                'id' => '33',
                'product_category_id' => '305',
                'parent_id' => NULL,
                'lft' => '55',
                'rght' => '56',
                'name' => 'specs',
            ],
            [
                'id' => '34',
                'product_category_id' => '305',
                'parent_id' => NULL,
                'lft' => '57',
                'rght' => '58',
                'name' => 'Nike',
            ],
            [
                'id' => '35',
                'product_category_id' => '305',
                'parent_id' => NULL,
                'lft' => '59',
                'rght' => '60',
                'name' => 'Adidas',
            ],
            [
                'id' => '36',
                'product_category_id' => '401',
                'parent_id' => NULL,
                'lft' => '61',
                'rght' => '62',
                'name' => 'APPLE',
            ],
            [
                'id' => '37',
                'product_category_id' => '408',
                'parent_id' => NULL,
                'lft' => '63',
                'rght' => '64',
                'name' => 'AMBIGO',
            ],
            [
                'id' => '38',
                'product_category_id' => '94',
                'parent_id' => NULL,
                'lft' => '65',
                'rght' => '66',
                'name' => 'HEM',
            ],
            [
                'id' => '39',
                'product_category_id' => '89',
                'parent_id' => NULL,
                'lft' => '67',
                'rght' => '68',
                'name' => 'GTMAN',
            ],
            [
                'id' => '40',
                'product_category_id' => '76',
                'parent_id' => NULL,
                'lft' => '69',
                'rght' => '70',
                'name' => 'WAY OF MAN',
            ],
            [
                'id' => '41',
                'product_category_id' => '17',
                'parent_id' => NULL,
                'lft' => '71',
                'rght' => '72',
                'name' => 'Hoodieku',
            ],
            [
                'id' => '42',
                'product_category_id' => '317',
                'parent_id' => NULL,
                'lft' => '73',
                'rght' => '74',
                'name' => 'EVERLAST',
            ],
            [
                'id' => '43',
                'product_category_id' => '431',
                'parent_id' => NULL,
                'lft' => '75',
                'rght' => '76',
                'name' => 'Logitech',
            ],
            [
                'id' => '44',
                'product_category_id' => '213',
                'parent_id' => NULL,
                'lft' => '77',
                'rght' => '78',
                'name' => 'MAMYPOPOK',
            ],
            [
                'id' => '45',
                'product_category_id' => '239',
                'parent_id' => NULL,
                'lft' => '79',
                'rght' => '80',
                'name' => 'Tamago Shoes',
            ],
            [
                'id' => '46',
                'product_category_id' => '126',
                'parent_id' => NULL,
                'lft' => '81',
                'rght' => '82',
                'name' => 'Gorden Blackout',
            ],
            [
                'id' => '47',
                'product_category_id' => '150',
                'parent_id' => NULL,
                'lft' => '83',
                'rght' => '84',
                'name' => 'Mustika Sprei',
            ],
            [
                'id' => '48',
                'product_category_id' => '43',
                'parent_id' => NULL,
                'lft' => '85',
                'rght' => '86',
                'name' => 'VANS',
            ],
            [
                'id' => '49',
                'product_category_id' => '150',
                'parent_id' => NULL,
                'lft' => '87',
                'rght' => '88',
                'name' => 'Royal Sprei',
            ],
            [
                'id' => '50',
                'product_category_id' => '432',
                'parent_id' => NULL,
                'lft' => '89',
                'rght' => '90',
                'name' => 'Logitech',
            ],
            [
                'id' => '51',
                'product_category_id' => '17',
                'parent_id' => NULL,
                'lft' => '91',
                'rght' => '92',
                'name' => 'MOCHA',
            ],
            [
                'id' => '52',
                'product_category_id' => '303',
                'parent_id' => NULL,
                'lft' => '93',
                'rght' => '94',
                'name' => 'Yonex',
            ],
            [
                'id' => '53',
                'product_category_id' => '303',
                'parent_id' => NULL,
                'lft' => '95',
                'rght' => '96',
                'name' => 'Li-Ning',
            ],
            [
                'id' => '54',
                'product_category_id' => '435',
                'parent_id' => NULL,
                'lft' => '97',
                'rght' => '98',
                'name' => 'Sony',
            ],
            [
                'id' => '55',
                'product_category_id' => '311',
                'parent_id' => NULL,
                'lft' => '99',
                'rght' => '100',
                'name' => 'KIA',
            ],
            [
                'id' => '56',
                'product_category_id' => '446',
                'parent_id' => NULL,
                'lft' => '101',
                'rght' => '102',
                'name' => 'CameraLog',
            ],
            [
                'id' => '57',
                'product_category_id' => '404',
                'parent_id' => NULL,
                'lft' => '103',
                'rght' => '104',
                'name' => 'Xiaomi',
            ],
            [
                'id' => '58',
                'product_category_id' => '70',
                'parent_id' => NULL,
                'lft' => '105',
                'rght' => '106',
                'name' => 'COOLIST',
            ],
            [
                'id' => '59',
                'product_category_id' => '105',
                'parent_id' => NULL,
                'lft' => '107',
                'rght' => '108',
                'name' => 'Tupperware',
            ],
            [
                'id' => '60',
                'product_category_id' => '104',
                'parent_id' => NULL,
                'lft' => '109',
                'rght' => '110',
                'name' => 'PTC',
            ],
            [
                'id' => '61',
                'product_category_id' => '114',
                'parent_id' => NULL,
                'lft' => '111',
                'rght' => '112',
                'name' => 'HOME STAFF',
            ],
            [
                'id' => '62',
                'product_category_id' => '148',
                'parent_id' => NULL,
                'lft' => '113',
                'rght' => '114',
                'name' => 'GOTO',
            ],
        ];

        $table = $this->table('brands');
        $table->insert($data)->save();
    }
}
