<?php
use Migrations\AbstractSeed;

/**
 * ProductOptionValueLists seed.
 */
class ProductOptionValueListsSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '2',
                'product_option_price_id' => '2',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '3',
                'product_option_price_id' => '3',
                'option_id' => '1',
                'option_value_id' => '20',
            ],
            [
                'id' => '4',
                'product_option_price_id' => '4',
                'option_id' => '1',
                'option_value_id' => '21',
            ],
            [
                'id' => '5',
                'product_option_price_id' => '5',
                'option_id' => '1',
                'option_value_id' => '23',
            ],
            [
                'id' => '6',
                'product_option_price_id' => '6',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '7',
                'product_option_price_id' => '7',
                'option_id' => '1',
                'option_value_id' => '12',
            ],
            [
                'id' => '8',
                'product_option_price_id' => '8',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '9',
                'product_option_price_id' => '9',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '10',
                'product_option_price_id' => '10',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '11',
                'product_option_price_id' => '11',
                'option_id' => '1',
                'option_value_id' => '24',
            ],
            [
                'id' => '12',
                'product_option_price_id' => '11',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '13',
                'product_option_price_id' => '12',
                'option_id' => '1',
                'option_value_id' => '14',
            ],
            [
                'id' => '14',
                'product_option_price_id' => '12',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '15',
                'product_option_price_id' => '13',
                'option_id' => '1',
                'option_value_id' => '28',
            ],
            [
                'id' => '16',
                'product_option_price_id' => '13',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '17',
                'product_option_price_id' => '14',
                'option_id' => '1',
                'option_value_id' => '24',
            ],
            [
                'id' => '18',
                'product_option_price_id' => '14',
                'option_id' => '2',
                'option_value_id' => '26',
            ],
            [
                'id' => '19',
                'product_option_price_id' => '15',
                'option_id' => '1',
                'option_value_id' => '14',
            ],
            [
                'id' => '20',
                'product_option_price_id' => '15',
                'option_id' => '2',
                'option_value_id' => '26',
            ],
            [
                'id' => '21',
                'product_option_price_id' => '16',
                'option_id' => '1',
                'option_value_id' => '28',
            ],
            [
                'id' => '22',
                'product_option_price_id' => '16',
                'option_id' => '2',
                'option_value_id' => '26',
            ],
            [
                'id' => '23',
                'product_option_price_id' => '17',
                'option_id' => '1',
                'option_value_id' => '24',
            ],
            [
                'id' => '24',
                'product_option_price_id' => '17',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '25',
                'product_option_price_id' => '18',
                'option_id' => '1',
                'option_value_id' => '14',
            ],
            [
                'id' => '26',
                'product_option_price_id' => '18',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '27',
                'product_option_price_id' => '19',
                'option_id' => '1',
                'option_value_id' => '28',
            ],
            [
                'id' => '28',
                'product_option_price_id' => '19',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '29',
                'product_option_price_id' => '20',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '30',
                'product_option_price_id' => '21',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '31',
                'product_option_price_id' => '22',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '32',
                'product_option_price_id' => '23',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '33',
                'product_option_price_id' => '24',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '34',
                'product_option_price_id' => '25',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '35',
                'product_option_price_id' => '26',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '36',
                'product_option_price_id' => '26',
                'option_id' => '2',
                'option_value_id' => '29',
            ],
            [
                'id' => '37',
                'product_option_price_id' => '27',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '38',
                'product_option_price_id' => '27',
                'option_id' => '2',
                'option_value_id' => '29',
            ],
            [
                'id' => '39',
                'product_option_price_id' => '28',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '40',
                'product_option_price_id' => '28',
                'option_id' => '2',
                'option_value_id' => '29',
            ],
            [
                'id' => '41',
                'product_option_price_id' => '29',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '42',
                'product_option_price_id' => '29',
                'option_id' => '2',
                'option_value_id' => '30',
            ],
            [
                'id' => '43',
                'product_option_price_id' => '30',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '44',
                'product_option_price_id' => '30',
                'option_id' => '2',
                'option_value_id' => '30',
            ],
            [
                'id' => '45',
                'product_option_price_id' => '31',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '46',
                'product_option_price_id' => '31',
                'option_id' => '2',
                'option_value_id' => '30',
            ],
            [
                'id' => '47',
                'product_option_price_id' => '32',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '48',
                'product_option_price_id' => '32',
                'option_id' => '2',
                'option_value_id' => '18',
            ],
            [
                'id' => '49',
                'product_option_price_id' => '33',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '50',
                'product_option_price_id' => '33',
                'option_id' => '2',
                'option_value_id' => '18',
            ],
            [
                'id' => '51',
                'product_option_price_id' => '34',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '52',
                'product_option_price_id' => '34',
                'option_id' => '2',
                'option_value_id' => '18',
            ],
            [
                'id' => '53',
                'product_option_price_id' => '35',
                'option_id' => '1',
                'option_value_id' => '17',
            ],
            [
                'id' => '54',
                'product_option_price_id' => '35',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '55',
                'product_option_price_id' => '36',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '56',
                'product_option_price_id' => '36',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '57',
                'product_option_price_id' => '37',
                'option_id' => '1',
                'option_value_id' => '17',
            ],
            [
                'id' => '58',
                'product_option_price_id' => '37',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '59',
                'product_option_price_id' => '38',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '60',
                'product_option_price_id' => '38',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '61',
                'product_option_price_id' => '39',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '62',
                'product_option_price_id' => '39',
                'option_id' => '2',
                'option_value_id' => '35',
            ],
            [
                'id' => '63',
                'product_option_price_id' => '40',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '64',
                'product_option_price_id' => '40',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '65',
                'product_option_price_id' => '41',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '66',
                'product_option_price_id' => '41',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '67',
                'product_option_price_id' => '42',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '68',
                'product_option_price_id' => '42',
                'option_id' => '2',
                'option_value_id' => '36',
            ],
            [
                'id' => '69',
                'product_option_price_id' => '43',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '70',
                'product_option_price_id' => '43',
                'option_id' => '2',
                'option_value_id' => '35',
            ],
            [
                'id' => '71',
                'product_option_price_id' => '44',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '72',
                'product_option_price_id' => '44',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '73',
                'product_option_price_id' => '45',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '74',
                'product_option_price_id' => '45',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '75',
                'product_option_price_id' => '46',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '76',
                'product_option_price_id' => '46',
                'option_id' => '2',
                'option_value_id' => '36',
            ],
            [
                'id' => '77',
                'product_option_price_id' => '47',
                'option_id' => '1',
                'option_value_id' => '37',
            ],
            [
                'id' => '78',
                'product_option_price_id' => '47',
                'option_id' => '2',
                'option_value_id' => '35',
            ],
            [
                'id' => '79',
                'product_option_price_id' => '48',
                'option_id' => '1',
                'option_value_id' => '37',
            ],
            [
                'id' => '80',
                'product_option_price_id' => '48',
                'option_id' => '2',
                'option_value_id' => '25',
            ],
            [
                'id' => '81',
                'product_option_price_id' => '49',
                'option_id' => '1',
                'option_value_id' => '37',
            ],
            [
                'id' => '82',
                'product_option_price_id' => '49',
                'option_id' => '2',
                'option_value_id' => '27',
            ],
            [
                'id' => '83',
                'product_option_price_id' => '50',
                'option_id' => '1',
                'option_value_id' => '37',
            ],
            [
                'id' => '84',
                'product_option_price_id' => '50',
                'option_id' => '2',
                'option_value_id' => '36',
            ],
            [
                'id' => '85',
                'product_option_price_id' => '51',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '86',
                'product_option_price_id' => '52',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '87',
                'product_option_price_id' => '53',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '88',
                'product_option_price_id' => '54',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '89',
                'product_option_price_id' => '55',
                'option_id' => '1',
                'option_value_id' => '14',
            ],
            [
                'id' => '90',
                'product_option_price_id' => '56',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '91',
                'product_option_price_id' => '56',
                'option_id' => '2',
                'option_value_id' => '16',
            ],
            [
                'id' => '92',
                'product_option_price_id' => '57',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '93',
                'product_option_price_id' => '57',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '94',
                'product_option_price_id' => '58',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '95',
                'product_option_price_id' => '58',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '96',
                'product_option_price_id' => '59',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '97',
                'product_option_price_id' => '59',
                'option_id' => '2',
                'option_value_id' => '16',
            ],
            [
                'id' => '98',
                'product_option_price_id' => '60',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '99',
                'product_option_price_id' => '60',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '100',
                'product_option_price_id' => '61',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '101',
                'product_option_price_id' => '61',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '102',
                'product_option_price_id' => '62',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '103',
                'product_option_price_id' => '62',
                'option_id' => '2',
                'option_value_id' => '16',
            ],
            [
                'id' => '104',
                'product_option_price_id' => '63',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '105',
                'product_option_price_id' => '63',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '106',
                'product_option_price_id' => '64',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '107',
                'product_option_price_id' => '64',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '108',
                'product_option_price_id' => '65',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '109',
                'product_option_price_id' => '66',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '110',
                'product_option_price_id' => '67',
                'option_id' => '2',
                'option_value_id' => '16',
            ],
            [
                'id' => '111',
                'product_option_price_id' => '68',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '112',
                'product_option_price_id' => '69',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '113',
                'product_option_price_id' => '70',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '114',
                'product_option_price_id' => '71',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '115',
                'product_option_price_id' => '72',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '116',
                'product_option_price_id' => '73',
                'option_id' => '1',
                'option_value_id' => '6',
            ],
            [
                'id' => '117',
                'product_option_price_id' => '74',
                'option_id' => '1',
                'option_value_id' => '15',
            ],
            [
                'id' => '118',
                'product_option_price_id' => '75',
                'option_id' => '1',
                'option_value_id' => '39',
            ],
            [
                'id' => '119',
                'product_option_price_id' => '76',
                'option_id' => '2',
                'option_value_id' => '38',
            ],
            [
                'id' => '120',
                'product_option_price_id' => '77',
                'option_id' => '2',
                'option_value_id' => '40',
            ],
            [
                'id' => '121',
                'product_option_price_id' => '78',
                'option_id' => '2',
                'option_value_id' => '41',
            ],
            [
                'id' => '122',
                'product_option_price_id' => '79',
                'option_id' => '2',
                'option_value_id' => '29',
            ],
            [
                'id' => '123',
                'product_option_price_id' => '80',
                'option_id' => '2',
                'option_value_id' => '30',
            ],
            [
                'id' => '124',
                'product_option_price_id' => '81',
                'option_id' => '1',
                'option_value_id' => '6',
            ],
            [
                'id' => '125',
                'product_option_price_id' => '82',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '126',
                'product_option_price_id' => '83',
                'option_id' => '1',
                'option_value_id' => '42',
            ],
            [
                'id' => '127',
                'product_option_price_id' => '84',
                'option_id' => '1',
                'option_value_id' => '43',
            ],
            [
                'id' => '128',
                'product_option_price_id' => '85',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '129',
                'product_option_price_id' => '85',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '130',
                'product_option_price_id' => '86',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '131',
                'product_option_price_id' => '86',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '132',
                'product_option_price_id' => '87',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '133',
                'product_option_price_id' => '87',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '134',
                'product_option_price_id' => '88',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '135',
                'product_option_price_id' => '88',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '136',
                'product_option_price_id' => '89',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '137',
                'product_option_price_id' => '89',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '138',
                'product_option_price_id' => '90',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '139',
                'product_option_price_id' => '90',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '140',
                'product_option_price_id' => '91',
                'option_id' => '1',
                'option_value_id' => '20',
            ],
            [
                'id' => '141',
                'product_option_price_id' => '91',
                'option_id' => '2',
                'option_value_id' => '31',
            ],
            [
                'id' => '142',
                'product_option_price_id' => '92',
                'option_id' => '1',
                'option_value_id' => '20',
            ],
            [
                'id' => '143',
                'product_option_price_id' => '92',
                'option_id' => '2',
                'option_value_id' => '32',
            ],
            [
                'id' => '144',
                'product_option_price_id' => '93',
                'option_id' => '1',
                'option_value_id' => '20',
            ],
            [
                'id' => '145',
                'product_option_price_id' => '93',
                'option_id' => '2',
                'option_value_id' => '33',
            ],
            [
                'id' => '146',
                'product_option_price_id' => '94',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '147',
                'product_option_price_id' => '95',
                'option_id' => '1',
                'option_value_id' => '6',
            ],
            [
                'id' => '148',
                'product_option_price_id' => '96',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '149',
                'product_option_price_id' => '97',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '150',
                'product_option_price_id' => '98',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '151',
                'product_option_price_id' => '99',
                'option_id' => '1',
                'option_value_id' => '14',
            ],
            [
                'id' => '152',
                'product_option_price_id' => '100',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '153',
                'product_option_price_id' => '101',
                'option_id' => '1',
                'option_value_id' => '6',
            ],
            [
                'id' => '154',
                'product_option_price_id' => '102',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '155',
                'product_option_price_id' => '103',
                'option_id' => '1',
                'option_value_id' => '22',
            ],
            [
                'id' => '156',
                'product_option_price_id' => '104',
                'option_id' => '1',
                'option_value_id' => '17',
            ],
            [
                'id' => '157',
                'product_option_price_id' => '105',
                'option_id' => '1',
                'option_value_id' => '17',
            ],
            [
                'id' => '158',
                'product_option_price_id' => '106',
                'option_id' => '1',
                'option_value_id' => '1',
            ],
            [
                'id' => '159',
                'product_option_price_id' => '107',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '160',
                'product_option_price_id' => '108',
                'option_id' => '1',
                'option_value_id' => '15',
            ],
            [
                'id' => '161',
                'product_option_price_id' => '109',
                'option_id' => '1',
                'option_value_id' => '17',
            ],
            [
                'id' => '162',
                'product_option_price_id' => '110',
                'option_id' => '1',
                'option_value_id' => '34',
            ],
            [
                'id' => '163',
                'product_option_price_id' => '111',
                'option_id' => '1',
                'option_value_id' => '20',
            ],
            [
                'id' => '164',
                'product_option_price_id' => '112',
                'option_id' => '1',
                'option_value_id' => '5',
            ],
            [
                'id' => '165',
                'product_option_price_id' => '113',
                'option_id' => '1',
                'option_value_id' => '2',
            ],
            [
                'id' => '166',
                'product_option_price_id' => '114',
                'option_id' => '1',
                'option_value_id' => '15',
            ],
        ];

        $table = $this->table('product_option_value_lists');
        $table->insert($data)->save();
    }
}
