<?php
use Migrations\AbstractSeed;

/**
 * ProductAttributes seed.
 */
class ProductAttributesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '40',
                'product_id' => '11',
                'attribute_name_id' => '72',
                'attribute_id' => '74',
                'description' => '',
            ],
            [
                'id' => '41',
                'product_id' => '11',
                'attribute_name_id' => '72',
                'attribute_id' => '75',
                'description' => '',
            ],
            [
                'id' => '42',
                'product_id' => '11',
                'attribute_name_id' => '72',
                'attribute_id' => '76',
                'description' => '',
            ],
            [
                'id' => '43',
                'product_id' => '11',
                'attribute_name_id' => '77',
                'attribute_id' => '96',
                'description' => '',
            ],
            [
                'id' => '44',
                'product_id' => '11',
                'attribute_name_id' => '77',
                'attribute_id' => '97',
                'description' => '',
            ],
            [
                'id' => '45',
                'product_id' => '11',
                'attribute_name_id' => '77',
                'attribute_id' => '98',
                'description' => '',
            ],
            [
                'id' => '49',
                'product_id' => '19',
                'attribute_name_id' => '110',
                'attribute_id' => '111',
                'description' => '',
            ],
            [
                'id' => '50',
                'product_id' => '19',
                'attribute_name_id' => '110',
                'attribute_id' => '112',
                'description' => '',
            ],
            [
                'id' => '51',
                'product_id' => '19',
                'attribute_name_id' => '110',
                'attribute_id' => '113',
                'description' => '',
            ],
            [
                'id' => '52',
                'product_id' => '17',
                'attribute_name_id' => '114',
                'attribute_id' => '115',
                'description' => '',
            ],
            [
                'id' => '53',
                'product_id' => '17',
                'attribute_name_id' => '114',
                'attribute_id' => '116',
                'description' => '',
            ],
            [
                'id' => '54',
                'product_id' => '17',
                'attribute_name_id' => '114',
                'attribute_id' => '117',
                'description' => '',
            ],
            [
                'id' => '55',
                'product_id' => '23',
                'attribute_name_id' => '118',
                'attribute_id' => '119',
                'description' => '',
            ],
            [
                'id' => '56',
                'product_id' => '23',
                'attribute_name_id' => '118',
                'attribute_id' => '120',
                'description' => '',
            ],
            [
                'id' => '57',
                'product_id' => '23',
                'attribute_name_id' => '118',
                'attribute_id' => '121',
                'description' => '',
            ],
            [
                'id' => '58',
                'product_id' => '20',
                'attribute_name_id' => '34',
                'attribute_id' => '37',
                'description' => '',
            ],
            [
                'id' => '59',
                'product_id' => '20',
                'attribute_name_id' => '34',
                'attribute_id' => '38',
                'description' => '',
            ],
            [
                'id' => '60',
                'product_id' => '20',
                'attribute_name_id' => '34',
                'attribute_id' => '39',
                'description' => '',
            ],
            [
                'id' => '61',
                'product_id' => '20',
                'attribute_name_id' => '42',
                'attribute_id' => '44',
                'description' => '',
            ],
            [
                'id' => '62',
                'product_id' => '20',
                'attribute_name_id' => '42',
                'attribute_id' => '45',
                'description' => '',
            ],
            [
                'id' => '63',
                'product_id' => '20',
                'attribute_name_id' => '42',
                'attribute_id' => '46',
                'description' => '',
            ],
            [
                'id' => '64',
                'product_id' => '20',
                'attribute_name_id' => '49',
                'attribute_id' => '50',
                'description' => '',
            ],
            [
                'id' => '65',
                'product_id' => '29',
                'attribute_name_id' => '127',
                'attribute_id' => '129',
                'description' => '',
            ],
            [
                'id' => '66',
                'product_id' => '29',
                'attribute_name_id' => '127',
                'attribute_id' => '130',
                'description' => '',
            ],
            [
                'id' => '67',
                'product_id' => '29',
                'attribute_name_id' => '127',
                'attribute_id' => '131',
                'description' => '',
            ],
            [
                'id' => '68',
                'product_id' => '33',
                'attribute_name_id' => '133',
                'attribute_id' => '135',
                'description' => '',
            ],
            [
                'id' => '69',
                'product_id' => '33',
                'attribute_name_id' => '133',
                'attribute_id' => '136',
                'description' => '',
            ],
            [
                'id' => '70',
                'product_id' => '33',
                'attribute_name_id' => '133',
                'attribute_id' => '137',
                'description' => '',
            ],
            [
                'id' => '71',
                'product_id' => '34',
                'attribute_name_id' => '51',
                'attribute_id' => '58',
                'description' => '',
            ],
            [
                'id' => '72',
                'product_id' => '34',
                'attribute_name_id' => '51',
                'attribute_id' => '59',
                'description' => '',
            ],
            [
                'id' => '73',
                'product_id' => '34',
                'attribute_name_id' => '51',
                'attribute_id' => '60',
                'description' => '',
            ],
            [
                'id' => '74',
                'product_id' => '34',
                'attribute_name_id' => '64',
                'attribute_id' => '65',
                'description' => '',
            ],
            [
                'id' => '75',
                'product_id' => '34',
                'attribute_name_id' => '64',
                'attribute_id' => '70',
                'description' => '',
            ],
            [
                'id' => '76',
                'product_id' => '34',
                'attribute_name_id' => '64',
                'attribute_id' => '126',
                'description' => '',
            ],
            [
                'id' => '77',
                'product_id' => '38',
                'attribute_name_id' => '151',
                'attribute_id' => '152',
                'description' => '',
            ],
            [
                'id' => '78',
                'product_id' => '38',
                'attribute_name_id' => '151',
                'attribute_id' => '153',
                'description' => '',
            ],
            [
                'id' => '79',
                'product_id' => '38',
                'attribute_name_id' => '156',
                'attribute_id' => '158',
                'description' => '',
            ],
            [
                'id' => '80',
                'product_id' => '38',
                'attribute_name_id' => '156',
                'attribute_id' => '159',
                'description' => '',
            ],
            [
                'id' => '81',
                'product_id' => '37',
                'attribute_name_id' => '139',
                'attribute_id' => '140',
                'description' => '',
            ],
            [
                'id' => '82',
                'product_id' => '37',
                'attribute_name_id' => '139',
                'attribute_id' => '141',
                'description' => '',
            ],
            [
                'id' => '83',
                'product_id' => '37',
                'attribute_name_id' => '139',
                'attribute_id' => '142',
                'description' => '',
            ],
            [
                'id' => '84',
                'product_id' => '37',
                'attribute_name_id' => '143',
                'attribute_id' => '144',
                'description' => '',
            ],
            [
                'id' => '85',
                'product_id' => '37',
                'attribute_name_id' => '143',
                'attribute_id' => '146',
                'description' => '',
            ],
            [
                'id' => '86',
                'product_id' => '37',
                'attribute_name_id' => '143',
                'attribute_id' => '148',
                'description' => '',
            ],
            [
                'id' => '87',
                'product_id' => '37',
                'attribute_name_id' => '143',
                'attribute_id' => '150',
                'description' => '',
            ],
            [
                'id' => '88',
                'product_id' => '39',
                'attribute_name_id' => '72',
                'attribute_id' => '74',
                'description' => '',
            ],
            [
                'id' => '89',
                'product_id' => '39',
                'attribute_name_id' => '72',
                'attribute_id' => '75',
                'description' => '',
            ],
            [
                'id' => '90',
                'product_id' => '39',
                'attribute_name_id' => '77',
                'attribute_id' => '79',
                'description' => '',
            ],
            [
                'id' => '91',
                'product_id' => '42',
                'attribute_name_id' => '169',
                'attribute_id' => '170',
                'description' => '',
            ],
            [
                'id' => '92',
                'product_id' => '42',
                'attribute_name_id' => '169',
                'attribute_id' => '171',
                'description' => '',
            ],
            [
                'id' => '93',
                'product_id' => '42',
                'attribute_name_id' => '169',
                'attribute_id' => '173',
                'description' => '',
            ],
            [
                'id' => '94',
                'product_id' => '41',
                'attribute_name_id' => '161',
                'attribute_id' => '162',
                'description' => '',
            ],
            [
                'id' => '95',
                'product_id' => '41',
                'attribute_name_id' => '161',
                'attribute_id' => '163',
                'description' => '',
            ],
            [
                'id' => '96',
                'product_id' => '41',
                'attribute_name_id' => '161',
                'attribute_id' => '164',
                'description' => '',
            ],
            [
                'id' => '97',
                'product_id' => '41',
                'attribute_name_id' => '165',
                'attribute_id' => '166',
                'description' => '',
            ],
            [
                'id' => '98',
                'product_id' => '41',
                'attribute_name_id' => '165',
                'attribute_id' => '167',
                'description' => '',
            ],
            [
                'id' => '99',
                'product_id' => '41',
                'attribute_name_id' => '165',
                'attribute_id' => '168',
                'description' => '',
            ],
            [
                'id' => '100',
                'product_id' => '46',
                'attribute_name_id' => '180',
                'attribute_id' => '188',
                'description' => '',
            ],
            [
                'id' => '101',
                'product_id' => '46',
                'attribute_name_id' => '184',
                'attribute_id' => '186',
                'description' => '',
            ],
            [
                'id' => '102',
                'product_id' => '46',
                'attribute_name_id' => '184',
                'attribute_id' => '187',
                'description' => '',
            ],
            [
                'id' => '103',
                'product_id' => '44',
                'attribute_name_id' => '175',
                'attribute_id' => '176',
                'description' => '',
            ],
            [
                'id' => '104',
                'product_id' => '44',
                'attribute_name_id' => '175',
                'attribute_id' => '177',
                'description' => '',
            ],
            [
                'id' => '105',
                'product_id' => '44',
                'attribute_name_id' => '175',
                'attribute_id' => '178',
                'description' => '',
            ],
            [
                'id' => '106',
                'product_id' => '44',
                'attribute_name_id' => '175',
                'attribute_id' => '179',
                'description' => '',
            ],
            [
                'id' => '107',
                'product_id' => '47',
                'attribute_name_id' => '189',
                'attribute_id' => '190',
                'description' => '',
            ],
            [
                'id' => '108',
                'product_id' => '47',
                'attribute_name_id' => '189',
                'attribute_id' => '192',
                'description' => '',
            ],
            [
                'id' => '109',
                'product_id' => '50',
                'attribute_name_id' => '202',
                'attribute_id' => '203',
                'description' => '',
            ],
            [
                'id' => '110',
                'product_id' => '50',
                'attribute_name_id' => '202',
                'attribute_id' => '204',
                'description' => '',
            ],
            [
                'id' => '111',
                'product_id' => '50',
                'attribute_name_id' => '202',
                'attribute_id' => '205',
                'description' => '',
            ],
            [
                'id' => '112',
                'product_id' => '48',
                'attribute_name_id' => '81',
                'attribute_id' => '85',
                'description' => '',
            ],
            [
                'id' => '113',
                'product_id' => '48',
                'attribute_name_id' => '81',
                'attribute_id' => '86',
                'description' => '',
            ],
            [
                'id' => '114',
                'product_id' => '48',
                'attribute_name_id' => '81',
                'attribute_id' => '87',
                'description' => '',
            ],
            [
                'id' => '115',
                'product_id' => '48',
                'attribute_name_id' => '81',
                'attribute_id' => '88',
                'description' => '',
            ],
            [
                'id' => '116',
                'product_id' => '48',
                'attribute_name_id' => '81',
                'attribute_id' => '89',
                'description' => '',
            ],
            [
                'id' => '117',
                'product_id' => '48',
                'attribute_name_id' => '90',
                'attribute_id' => '95',
                'description' => '',
            ],
            [
                'id' => '118',
                'product_id' => '52',
                'attribute_name_id' => '208',
                'attribute_id' => '209',
                'description' => '',
            ],
            [
                'id' => '119',
                'product_id' => '52',
                'attribute_name_id' => '208',
                'attribute_id' => '210',
                'description' => '',
            ],
            [
                'id' => '120',
                'product_id' => '54',
                'attribute_name_id' => '216',
                'attribute_id' => '217',
                'description' => '',
            ],
            [
                'id' => '121',
                'product_id' => '54',
                'attribute_name_id' => '216',
                'attribute_id' => '221',
                'description' => '',
            ],
            [
                'id' => '122',
                'product_id' => '53',
                'attribute_name_id' => '151',
                'attribute_id' => '213',
                'description' => '',
            ],
            [
                'id' => '123',
                'product_id' => '53',
                'attribute_name_id' => '151',
                'attribute_id' => '214',
                'description' => '',
            ],
            [
                'id' => '124',
                'product_id' => '53',
                'attribute_name_id' => '151',
                'attribute_id' => '215',
                'description' => '',
            ],
            [
                'id' => '125',
                'product_id' => '53',
                'attribute_name_id' => '156',
                'attribute_id' => '158',
                'description' => '',
            ],
            [
                'id' => '126',
                'product_id' => '53',
                'attribute_name_id' => '156',
                'attribute_id' => '159',
                'description' => '',
            ],
            [
                'id' => '127',
                'product_id' => '53',
                'attribute_name_id' => '156',
                'attribute_id' => '160',
                'description' => '',
            ],
            [
                'id' => '128',
                'product_id' => '55',
                'attribute_name_id' => '224',
                'attribute_id' => '225',
                'description' => '',
            ],
            [
                'id' => '129',
                'product_id' => '55',
                'attribute_name_id' => '224',
                'attribute_id' => '226',
                'description' => '',
            ],
            [
                'id' => '130',
                'product_id' => '56',
                'attribute_name_id' => '228',
                'attribute_id' => '229',
                'description' => '',
            ],
            [
                'id' => '131',
                'product_id' => '56',
                'attribute_name_id' => '228',
                'attribute_id' => '231',
                'description' => '',
            ],
            [
                'id' => '132',
                'product_id' => '57',
                'attribute_name_id' => '232',
                'attribute_id' => '234',
                'description' => '',
            ],
            [
                'id' => '133',
                'product_id' => '57',
                'attribute_name_id' => '232',
                'attribute_id' => '235',
                'description' => '',
            ],
            [
                'id' => '134',
                'product_id' => '58',
                'attribute_name_id' => '237',
                'attribute_id' => '238',
                'description' => '',
            ],
            [
                'id' => '135',
                'product_id' => '58',
                'attribute_name_id' => '237',
                'attribute_id' => '239',
                'description' => '',
            ],
            [
                'id' => '136',
                'product_id' => '61',
                'attribute_name_id' => '251',
                'attribute_id' => '252',
                'description' => '',
            ],
            [
                'id' => '137',
                'product_id' => '61',
                'attribute_name_id' => '251',
                'attribute_id' => '256',
                'description' => '',
            ],
            [
                'id' => '138',
                'product_id' => '61',
                'attribute_name_id' => '251',
                'attribute_id' => '257',
                'description' => '',
            ],
            [
                'id' => '139',
                'product_id' => '64',
                'attribute_name_id' => '258',
                'attribute_id' => '259',
                'description' => '',
            ],
            [
                'id' => '140',
                'product_id' => '64',
                'attribute_name_id' => '258',
                'attribute_id' => '260',
                'description' => '',
            ],
            [
                'id' => '141',
                'product_id' => '64',
                'attribute_name_id' => '258',
                'attribute_id' => '261',
                'description' => '',
            ],
            [
                'id' => '142',
                'product_id' => '65',
                'attribute_name_id' => '262',
                'attribute_id' => '263',
                'description' => '',
            ],
            [
                'id' => '143',
                'product_id' => '65',
                'attribute_name_id' => '262',
                'attribute_id' => '264',
                'description' => '',
            ],
            [
                'id' => '144',
                'product_id' => '65',
                'attribute_name_id' => '262',
                'attribute_id' => '265',
                'description' => '',
            ],
            [
                'id' => '145',
                'product_id' => '65',
                'attribute_name_id' => '262',
                'attribute_id' => '266',
                'description' => '',
            ],
            [
                'id' => '146',
                'product_id' => '67',
                'attribute_name_id' => '267',
                'attribute_id' => '268',
                'description' => '',
            ],
            [
                'id' => '147',
                'product_id' => '67',
                'attribute_name_id' => '267',
                'attribute_id' => '269',
                'description' => '',
            ],
            [
                'id' => '148',
                'product_id' => '67',
                'attribute_name_id' => '267',
                'attribute_id' => '270',
                'description' => '',
            ],
        ];

        $table = $this->table('product_attributes');
        $table->insert($data)->save();
    }
}
